import type { Expert, Project, Company } from "./types";

export const EXPERTS: Expert[] = [
  {
    id: "e1",
    name: "김재원",
    title: "前 현대중공업 조선사업부 부사장",
    company: "현대중공업",
    industries: ["shipbuilding", "manufacturing"],
    skills: ["선박 수주", "해외 영업", "EPC 계약"],
    yearsExp: 32,
    rating: 4.97,
    reviewCount: 43,
    hourlyRate: 35,
    available: true,
    location: "서울 / 화상 가능",
    avatar: "김재원",
    bio: "32년간 현대중공업 조선사업부에서 근무하며 누적 수주액 120억 달러를 달성했습니다. 중동, 유럽 선주사와의 협상 경험과 EPC 계약 전문 역량을 보유하고 있습니다.",
    completedProjects: 43,
    badge: "TOP",
    responseTime: "2h",
  },
  {
    id: "e2",
    name: "박수연",
    title: "前 카카오 CPO / 現 스타트업 어드바이저",
    company: "카카오",
    industries: ["it", "startup"],
    skills: ["제품 전략", "AI/ML 기획", "Series B+"],
    yearsExp: 18,
    rating: 4.95,
    reviewCount: 61,
    hourlyRate: 28,
    available: true,
    location: "서울",
    avatar: "박수연",
    bio: "카카오 CPO로 MAU 5천만 플랫폼을 운영했으며 현재 Series A~B 스타트업의 제품 전략과 AI 사업화 자문을 제공합니다.",
    completedProjects: 61,
    badge: "TOP",
    responseTime: "1h",
  },
  {
    id: "e3",
    name: "이현진",
    title: "前 삼성바이오로직스 CMC 본부장",
    company: "삼성바이오로직스",
    industries: ["healthcare"],
    skills: ["FDA 승인", "임상 전략", "CMC 대응"],
    yearsExp: 26,
    rating: 4.93,
    reviewCount: 29,
    hourlyRate: 40,
    available: false,
    availableFrom: "2026-06-01",
    location: "인천 / 화상 가능",
    avatar: "이현진",
    bio: "삼성바이오로직스에서 바이오 의약품 CMC 전략 수립 및 FDA/EMA 허가 대응 경험을 보유. 바이오벤처 IPO 전략 자문 전문.",
    completedProjects: 29,
    badge: "VERIFIED",
    responseTime: "4h",
  },
  {
    id: "e4",
    name: "최동훈",
    title: "前 KB증권 IB본부장 / 現 M&A 자문",
    company: "KB증권",
    industries: ["finance", "startup"],
    skills: ["IPO", "M&A", "Series C~Pre-IPO"],
    yearsExp: 24,
    rating: 4.91,
    reviewCount: 38,
    hourlyRate: 45,
    available: true,
    location: "서울",
    avatar: "최동훈",
    bio: "KB증권 IB본부장 출신으로 코스피·코스닥 상장 30건, M&A 딜 50건 이상의 실전 경험. IR 전략 수립부터 상장 전 투자자 관계까지 원스톱 자문 제공.",
    completedProjects: 38,
    badge: "TOP",
    responseTime: "3h",
  },
  {
    id: "e5",
    name: "정민아",
    title: "前 한화솔루션 중국법인장",
    company: "한화솔루션",
    industries: ["manufacturing", "energy"],
    skills: ["중국 시장 진출", "JV 설립", "현지 규제"],
    yearsExp: 21,
    rating: 4.88,
    reviewCount: 22,
    hourlyRate: 32,
    available: true,
    location: "서울 / 베이징",
    avatar: "정민아",
    bio: "한화솔루션 중국법인 설립부터 연 매출 3,000억 원 규모로 성장시킨 경험. 중국 정부 규제 대응, JV 설립, 현지 파트너 협상 전문.",
    completedProjects: 22,
    badge: "VERIFIED",
    responseTime: "6h",
  },
  {
    id: "e6",
    name: "강병철",
    title: "前 SKT CTO / AI 전략 컨설턴트",
    company: "SK텔레콤",
    industries: ["it", "startup"],
    skills: ["AI 전환", "기술 전략", "CTO 자문"],
    yearsExp: 28,
    rating: 4.96,
    reviewCount: 51,
    hourlyRate: 50,
    available: true,
    location: "서울 / 화상 가능",
    avatar: "강병철",
    bio: "SKT CTO 역임. 5G 상용화, AI/빅데이터 플랫폼 전략 수립 주도. 중견·대기업 AI 전환 로드맵 수립 및 기술 스택 선정 전문 자문.",
    completedProjects: 51,
    badge: "TOP",
    responseTime: "2h",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "p1",
    title: "중동 LNG 선박 수주 협상 기술 자문",
    company: "STX조선해양",
    industry: "조선·해양",
    type: "advisory",
    duration: "2주",
    budget: "500만원",
    urgent: true,
    ndaRequired: true,
    postedAt: "2026-05-18",
    status: "open",
    skills: ["선박 수주", "LNG 기술", "중동 영업"],
    description: "카타르 에너지사와의 LNG 선박 수주 협상에서 기술 검토 및 가격 협상 전략 자문이 필요합니다.",
    matchedExperts: 4,
  },
  {
    id: "p2",
    title: "Series A 투자 IR 자료 검토 및 피칭 코칭",
    company: "메디컬AI 스타트업",
    industry: "헬스케어·AI",
    type: "review",
    duration: "1주",
    budget: "200만원",
    urgent: false,
    ndaRequired: true,
    postedAt: "2026-05-17",
    status: "open",
    skills: ["IR 전략", "투자 유치", "헬스케어"],
    description: "글로벌 VC 대상 Series A IR 자료 검토 및 피칭 시뮬레이션 코칭을 요청드립니다.",
    matchedExperts: 7,
  },
  {
    id: "p3",
    title: "FDA 510(k) 허가 전략 자문",
    company: "코스맥스바이오",
    industry: "의료기기",
    type: "project",
    duration: "1개월",
    budget: "1,500만원",
    urgent: false,
    ndaRequired: true,
    postedAt: "2026-05-15",
    status: "matched",
    skills: ["FDA 허가", "510(k)", "의료기기"],
    description: "피부 진단 AI 디바이스의 미국 FDA 510(k) 허가 전략 수립 및 서류 검토 프로젝트.",
    matchedExperts: 2,
  },
  {
    id: "p4",
    title: "글로벌 SaaS 기업과의 기술 파트너십 협상",
    company: "핀테크 스타트업",
    industry: "IT·금융",
    type: "advisory",
    duration: "3일",
    budget: "300만원",
    urgent: true,
    ndaRequired: false,
    postedAt: "2026-05-18",
    status: "open",
    skills: ["BD", "SaaS", "기술 협상"],
    description: "Salesforce, HubSpot 등 글로벌 SaaS 플랫폼과의 파트너십 계약 협상 전략 및 계약 검토.",
    matchedExperts: 5,
  },
];

export const COMPANIES: Company[] = [
  { id: "c1", name: "현대중공업", industry: "조선", size: "대기업", logo: "현대" },
  { id: "c2", name: "카카오", industry: "IT", size: "대기업", logo: "카카오" },
  { id: "c3", name: "SK하이닉스", industry: "반도체", size: "대기업", logo: "SK" },
  { id: "c4", name: "셀트리온", industry: "바이오", size: "대기업", logo: "셀트" },
  { id: "c5", name: "쿠팡", industry: "이커머스", size: "대기업", logo: "쿠팡" },
  { id: "c6", name: "한화", industry: "방산·에너지", size: "대기업", logo: "한화" },
];

export const STATS = {
  experts: "2,400+",
  companies: "850+",
  avgResponseTime: "2.3h",
  successRate: "97%",
  avgYearsExp: 24,
  avgSaving: "68%",
};
