-- 0003_api_exposure.sql · 명시적 anon/authenticated 권한 부여
-- ADR-005 원칙: 기본 deny · 필요 엔드포인트만 개별 허용

-- PostgREST가 테이블을 노출하려면 schema usage + select grant가 필요
grant usage on schema public to anon, authenticated;

-- 공개 참조 데이터 (인증 불필요)
grant select on public.regions to anon, authenticated;

-- 공개 공고 읽기 (RLS policy `jobs_public_read` 가 status='open' 제한)
grant select on public.jobs to anon, authenticated;

-- 인증 사용자 전용
grant select, update on public.profiles to authenticated;
grant select, update on public.workers to authenticated;
grant select, update on public.employers to authenticated;
grant select on public.employer_members to authenticated;
grant select, insert on public.job_applications to authenticated;
grant select, update on public.matches to authenticated;
grant select, insert, update on public.shifts to authenticated;
grant select on public.payments to authenticated;
grant select on public.notifications to authenticated;
grant select on public.cx_tickets to authenticated;
grant select, insert on public.reviews to authenticated;

-- shifts INSERT 는 시스템(Edge Function service_role)만 — authenticated 는 update만
-- matches INSERT 는 시스템만

-- sequences (autogenerated id 지원)
grant usage, select on all sequences in schema public to authenticated;

-- regions: 법정동 참조 데이터는 공개 읽기 허용
alter table public.regions enable row level security;
drop policy if exists regions_public_read on public.regions;
create policy regions_public_read on public.regions
  for select using (true);
